event_management/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from events.views import home, contact, aboutUs
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('contact/', contact),
    path('aboutus/', aboutUs),
    path('events/', include("events.urls")),     
    path('', include("users.urls")),     
    path('', include('events.urls')),        
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users import views
from .views import (CustomLoginView, CustomLogoutView, admin_dashboard, 
                    participant_dashboard, organizer_dashboard, 
                    edit_participant, delete_participant,  
                    group_list, organizer_detail, add_group,
                    edit_group, delete_group,  participant_detail, participant_list,
                    activate_account,EditOrganizer, DeleteOrganizer, AddParticipant, SignupView, OrganizerListView, AddOrganizer,
                    ProfileView, EditProfileView, CustomPasswordChangeView, CustomPasswordChangeDoneView,
                    CustomPasswordResetView, CustomPasswordResetDoneView, CustomPasswordResetConfirmView, 
                    CustomPasswordResetCompleteView,
)
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
        
    # Auth

    # path("sign-up/", signup_view, name="signup"),
    path("sign-up/", SignupView.as_view(), name="signup"),
    path("sign-in/", CustomLoginView.as_view(), name="login"),
    path("users/logout/", CustomLogoutView.as_view(), name="logout"),
    path('activate/<uidb64>/<token>/', activate_account, name='activate_account'),
    

    path("dashboard/admin/", admin_dashboard, name="admin_dashboard"),
    path("dashboard/organizer/", organizer_dashboard, name="organizer_dashboard"),
    path("dashboard/participant/", participant_dashboard, name="participant_dashboard"),
    
    # Organizers

    # path('organizers/', organizer_list, name='organizer_list'),
    path('organizers/', OrganizerListView.as_view(), name='organizer_list'),
    # path('organizers/add/', add_organizer, name='add_organizer'),
    path('organizers/add/', AddOrganizer.as_view(), name='add_organizer'),
    # path('organizers/edit/<int:user_id>/', edit_organizer, name='edit_organizer'),
    path('organizer/edit/<int:user_id>/', EditOrganizer.as_view(), name='edit_organizer'),
    # path('organizers/delete/<int:user_id>/', delete_organizer, name='delete_organizer'),
    path('organizers/delete/<int:user_id>/', DeleteOrganizer.as_view(), name='delete_organizer'),

    path('organizers/<int:user_id>/', organizer_detail, name='organizer_detail'),
    path('promote-participant/', views.promote_from_participants, name='promote_from_participants'),


    # Groups

    path('groups/', group_list, name='group_list'),
    path('groups/add/', add_group, name='add_group'),
    path('groups/edit/<int:group_id>/', edit_group, name='edit_group'),
    path('groups/delete/<int:group_id>/', delete_group, name='delete_group'),

    # Participants

    path('participants/', participant_list, name='participant_list'),
    # path('participants/add/', add_participant, name='add_participant'),
    path('participants/add/', AddParticipant.as_view(), name='add_participant'),
    path('participants/edit/<int:user_id>/', edit_participant, name='edit_participant'),
    path('participants/delete/<int:user_id>/', delete_participant, name='delete_participant'),
    path('participants/<int:user_id>/', participant_detail, name='participant_detail'),


    # profile
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/edit/', EditProfileView.as_view(), name='edit_profile'),


    # password related
    path('password/change/', CustomPasswordChangeView.as_view(), name='password_change'),
    path('password/change/done/', CustomPasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password/reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password/reset/done/', CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password/reset/confirm/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password/reset/complete/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),

    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

events/models.py
from django.db import models
from django.conf import settings  

class Category(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name


class Event(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    date = models.DateField()
    time = models.TimeField()
    location = models.CharField(max_length=255)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    image = models.ImageField(
        upload_to='event_images/',
        default='event_images/default.jpg',
        blank=True
    )
    
    # AUTH_USER_MODEL
    participants = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="rsvped_events", blank=True)
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='created_events')
    
    def __str__(self):
        return self.name

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.core.validators import RegexValidator

def user_profile_path(instance, filename):
    return f"profile_pics/{instance.username}/{filename}"

class CustomUser(AbstractUser):
    phone_number = models.CharField(
        max_length=17,
        blank=True,
        validators=[
            RegexValidator(
                regex=r'^\+?1?\d{9,15}$',
                message="Enter a valid phone number in the format: '+999999999'. Up to 15 digits allowed."
            )
        ]
    )
    profile_picture = models.ImageField(
        upload_to=user_profile_path,
        blank=True,
        default='default.png'
    )

    class Meta:
        verbose_name = "User"
        verbose_name_plural = "Users"

    def __str__(self):
        return self.get_full_name() or self.username

users/views.py
from django import forms
from django.conf import settings
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import Group
from django.contrib.auth import get_user_model
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import LoginView, LogoutView
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, redirect, render
from django.template.loader import render_to_string
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from events.models import Event
from .forms import CustomUserCreationForm, CustomUserChangeForm, CustomAuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views import View
from users.models import CustomUser
from django.views.generic import DeleteView
from django.views.generic import ListView
from .forms import CustomPasswordResetForm  

from django.contrib.auth.views import (
    PasswordChangeView,
    PasswordChangeDoneView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)



User = get_user_model()

def is_admin_group(user):
    return user.is_superuser or user.groups.filter(name="Admin").exists()

def is_organizer(user):
    return is_admin_group(user) or user.groups.filter(name="Organizer").exists()

def is_participant(user):
    return is_admin_group(user) or user.groups.filter(name="Participant").exists()

def get_user_role(user):
    if user.groups.filter(name="Admin").exists():
        return "admin"
    elif user.groups.filter(name="Organizer").exists():
        return "organizer"
    elif user.groups.filter(name="Participant").exists():
        return "participant"
    return None


# Converted into Classed Based Views

class SignupView(View):
    def get(self, request):
        form = CustomUserCreationForm()
        return render(request, "users/signup.html", {"form": form})

    def post(self, request):
        form = CustomUserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()

            participant_group, created = Group.objects.get_or_create(name='Participant')
            user.groups.add(participant_group)

            token = default_token_generator.make_token(user)
            uid = urlsafe_base64_encode(force_bytes(user.pk))

            activation_link = request.build_absolute_uri(
                reverse('activate_account', kwargs={'uidb64': uid, 'token': token})
            )

            subject = "Activate your account"
            message = render_to_string('users/activation_email.html', {
                'user': user,
                'activation_link': activation_link,
            })

            user_email = form.cleaned_data.get('email')
            send_mail(subject, message, settings.DEFAULT_FROM_EMAIL, [user_email], fail_silently=False)

            return render(request, "users/activation_sent.html")

        return render(request, "users/signup.html", {"form": form})


def activate_account(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        return redirect('home')
    else:
        return render(request, 'users/activation_invalid.html')

class CustomLoginView(LoginView):
    authentication_form = CustomAuthenticationForm
    template_name = "users/login.html"

    def form_valid(self, form):
        user = form.get_user()
        if not user.is_active:
            return render(self.request, 'users/activation_required.html')
        login(self.request, user)
        role = get_user_role(user)
        if role == "admin":
            return redirect("admin_dashboard")
        elif role == "organizer":
            return redirect("organizer_dashboard")
        elif role == "participant":
            return redirect("participant_dashboard")
        return redirect("home")

class CustomLogoutView(LogoutView):
    next_page = reverse_lazy("login")

@login_required
@user_passes_test(is_admin_group)
def promote_from_participants(request):
    participant_group = Group.objects.get(name="Participant")
    participants = User.objects.filter(groups=participant_group)

    if request.method == "POST":
        user_id = request.POST.get("user_id")
        user = get_object_or_404(User, id=user_id)
        organizer_group = Group.objects.get(name="Organizer")
        user.groups.remove(participant_group)
        user.groups.add(organizer_group)
        user.save()
        return redirect('promote_from_participants')

    return render(request, "users/promote_from_participants.html", {
        "participants": participants
    })



# Converted into Classed Based Views

class OrganizerListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = User
    template_name = "organizer/organizer_list.html"
    context_object_name = "organizers"

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.groups.filter(name="Admin").exists()

    def get_queryset(self):
        return User.objects.filter(groups__name="Organizer")


# Converted into Classed Based Views

# add organizer
class AddOrganizer(LoginRequiredMixin, UserPassesTestMixin, View): #add organizer
    def test_func(self):
        return self.request.user.is_superuser or self.request.user.groups.filter(name="Admin").exists()

    def get(self, request):
        form = CustomUserCreationForm()
        return render(request, "organizer/add_organizer.html", {"form": form})

    def post(self, request):
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            organizer_group, _ = Group.objects.get_or_create(name="Organizer")
            user.groups.add(organizer_group)
            return redirect("organizer_list")
        return render(request, "organizer/add_organizer.html", {"form": form})


# edit organizer

# Converted into Classed Based Views
class EditOrganizer(LoginRequiredMixin, UserPassesTestMixin, View):
    def test_func(self):
        return self.request.user.groups.filter(name="Admin").exists()

    def get(self, request, user_id):
        user = get_object_or_404(User, id=user_id, groups__name="Organizer")
        form = CustomUserChangeForm(instance=user)
        return render(request, "organizer/edit_organizer.html", {"form": form, "user": user})

    def post(self, request, user_id):
        user = get_object_or_404(User, id=user_id, groups__name="Organizer")
        form = CustomUserChangeForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            return redirect("organizer_list")
        return render(request, "organizer/edit_organizer.html", {"form": form, "user": user})


# Converted into Classed Based Views
class DeleteOrganizer(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = User
    template_name = "organizer/delete_organizer_confirm.html"
    success_url = reverse_lazy("organizer_list")
    pk_url_kwarg = 'user_id'

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.groups.filter(name="Admin").exists()

    def get_object(self, queryset=None):
        user = get_object_or_404(User, id=self.kwargs.get(self.pk_url_kwarg), groups__name="Organizer")
        return user

@login_required
@user_passes_test(is_admin_group)
def organizer_detail(request, user_id):
    user = get_object_or_404(User, id=user_id, groups__name="Organizer")
    return render(request, "organizer/organizer_detail.html", {"user": user})

class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ['name']

@login_required
@user_passes_test(is_admin_group)
def group_list(request):
    groups = Group.objects.all()
    return render(request, "groups/group_list.html", {"groups": groups})

@login_required
@user_passes_test(is_admin_group)
def add_group(request):
    if request.method == "POST":
        form = GroupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("group_list")
    else:
        form = GroupForm()
    return render(request, "groups/add_group.html", {"form": form})

@login_required
@user_passes_test(is_admin_group)
def edit_group(request, group_id):
    group = get_object_or_404(Group, id=group_id)
    if request.method == "POST":
        form = GroupForm(request.POST, instance=group)
        if form.is_valid():
            form.save()
            return redirect("group_list")
    else:
        form = GroupForm(instance=group)
    return render(request, "groups/edit_group.html", {"form": form, "group": group})

@login_required
@user_passes_test(is_admin_group)
def delete_group(request, group_id):
    group = get_object_or_404(Group, id=group_id)
    if request.method == "POST":
        group.delete()
        return redirect("group_list")
    return render(request, "groups/delete_group_confirm.html", {"group": group})



# Converted into Classed Based Views

class AddParticipant(LoginRequiredMixin, UserPassesTestMixin, View):
    def test_func(self):
        return self.request.user.is_superuser or self.request.user.groups.filter(name__in=["Admin", "Organizer"]).exists()

    def get(self, request):
        form = CustomUserCreationForm()
        return render(request, "participants/add_participant.html", {"form": form})

users/templates/users/activation_email.html
Hi {{ user.username }},

Thanks for signing up! Please click the link below to activate your account:

{{ activation_link }}

If you did not sign up for this account, please ignore this email.

users/templates/users/activation_invalid.html
{% extends "base.html" %}
{% block title %}Activation Invalid{% endblock %}

{% block content %}
  <div class="max-w-xl mx-auto mt-16 p-6 bg-red-100 border border-red-400 rounded text-center">
    <h1 class="text-2xl font-bold text-red-700 mb-4">Activation Link Invalid</h1>
    <p class="text-red-600 mb-6">
      Sorry, the activation link you used is invalid or has expired.
    </p>
    <a href="{% url 'signup' %}" class="inline-block bg-blue-600 text-white px-4 py-2 rounded hover:bg-blue-700 transition">
      Register Again
    </a>
  </div>
{% endblock %}

users/templates/users/activation_sent.html
{% extends "base.html" %}

{% block title %}Activation Email Sent{% endblock %}

{% block content %}
  <div class="max-w-xl mx-auto mt-20 text-center">
    <h2 class="text-3xl font-bold text-green-600">✅ Activation Email Sent!</h2>
    <p class="mt-4 text-gray-700">
      We've sent an activation link to your email address. Please check your inbox and follow the link to activate your account.
    </p>
    <p class="mt-4 text-sm text-gray-500">
      Didn’t receive the email? Check your spam folder or try signing up again.
    </p>
    <a href="{% url 'login' %}" class="mt-6 inline-block bg-blue-500 text-white px-6 py-2 rounded hover:bg-blue-600">
      Go to Login
    </a>
  </div>
{% endblock %}

users/templates/users/admin_dashboard.html
{% extends "base.html" %}
{% block title %}Admin Dashboard{% endblock %}

{% block content %}
<h1 class="text-3xl font-bold text-blue-700 mb-8 text-center my-8">👨Admin Dashboard</h1>

<div class="grid gap-6 sm:grid-cols-2 lg:grid-cols-4 mb-10">
  <div class="bg-white shadow-lg rounded-2xl p-6 hover:shadow-xl transition">
    <h2 class="text-gray-500 text-sm">Total Participants</h2>
    <p class="text-3xl font-bold text-blue-600 mt-2">{{ total_participants }}</p>
  </div>
  <div class="bg-white shadow-lg rounded-2xl p-6 hover:shadow-xl transition">
    <h2 class="text-gray-500 text-sm">Total Events</h2>
    <p class="text-3xl font-bold text-blue-600 mt-2">{{ total_events }}</p>
  </div>
  <div class="bg-white shadow-lg rounded-2xl p-6 hover:shadow-xl transition">
    <h2 class="text-gray-500 text-sm">Upcoming Events</h2>
    <p class="text-3xl font-bold text-green-600 mt-2">{{ upcoming_events }}</p>
  </div>
  <div class="bg-white shadow-lg rounded-2xl p-6 hover:shadow-xl transition">
    <h2 class="text-gray-500 text-sm">Past Events</h2>
    <p class="text-3xl font-bold text-red-600 mt-2">{{ past_events }}</p>
  </div>
</div>


<div class="grid gap-6 sm:grid-cols-2 lg:grid-cols-4 mb-10">
  <!-- Example stats cards here -->
</div>

<div class="my-16 flex flex-col sm:flex-row gap-4 justify-center w-fit mx-auto">
  <a href="{% url 'participant_list' %}" class="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600 transition text-center">Manage Participants</a>

  <a href="{% url 'organizer_list' %}" class="bg-green-500 text-white px-4 py-2 rounded hover:bg-green-600 transition text-center">Manage Organizers</a>

  <a href="{% url 'promote_from_participants' %}" class="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600">
  Promote Participant to Organizer
</a>

  <a href="{% url 'group_list' %}" class="bg-yellow-500 text-white px-4 py-2 rounded hover:bg-yellow-600 transition text-center">Manage Groups</a>

  <a href="{% url 'all_events' %}" class="bg-purple-500 text-white px-4 py-2 rounded hover:bg-purple-600 transition text-center">Manage Events</a>

  <a href="{% url 'category_list' %}" class="bg-indigo-500 text-white px-4 py-2 rounded hover:bg-indigo-600 transition text-center">Manage Categories</a>


</div>

{% endblock %}

users/templates/users/log_out.html
{% extends "base.html" %}

{% block title %}Signned Out{% endblock %}

{% block content %}
<div class="text-center mt-10">
  <h2 class="text-2xl font-semibold text-gray-800">You have been signned out.</h2>
  <p class="mt-2">
    <a href="{% url 'login' %}" class="text-blue-600 hover:underline">Sign back in</a> or
    <a href="/" class="text-blue-600 hover:underline">return to home</a>.
  </p>
</div>
{% endblock %}

users/templates/users/login.html
{% extends "base.html" %}
{% block title %}Login | Event Management{% endblock %}

{% block content %}
<div class="flex justify-center items-center min-h-[75vh] mb-16 px-4">
  <div class="bg-white shadow-2xl rounded-3xl w-full max-w-2xl p-10 sm:p-14">
    <div class="mb-10 text-center">
      <h2 class="text-4xl font-bold text-gray-800">Welcome Back</h2>
      <p class="text-gray-500 text-sm mt-2">Login to manage and attend events</p>
    </div>

    <form method="POST" class="space-y-6">
      {% csrf_token %}
      {% for field in form %}
        <div>
          <label class="block text-gray-700 font-semibold mb-1">{{ field.label }}</label>
          {{ field }}
          {% if field.errors %}
            <p class="text-sm text-red-500 mt-1">{{ field.errors.0 }}</p>
          {% endif %}
        </div>
      {% endfor %}
      <button
        type="submit"
        class="w-full bg-blue-600 hover:bg-blue-700 transition-all text-white font-bold py-3 rounded-xl text-lg shadow-sm"
      >
        Sign in
      </button>
    </form>

    <p class="text-sm text-gray-600 mt-6 text-center">
      Don't have an account?
      <a href="{% url 'signup' %}" class="text-blue-600 hover:underline font-semibold">Sign up here</a>
    </p>
    <p>
      <a href="{% url 'password_reset' %}">Forgot your password?</a>
    </p>
  </div>
</div>
{% endblock %}

users/templates/users/organizer_dashboard.html
{% extends "base.html" %}
{% block title %}Organizer Dashboard{% endblock %}

{% block content %}
<h1 class="text-3xl font-bold text-blue-700 mb-8 text-center my-8">📊 Organizer Dashboard</h1>

<div class="grid gap-6 sm:grid-cols-2 lg:grid-cols-4 mb-10">
  <div class="bg-white shadow-lg rounded-2xl p-6 hover:shadow-xl transition">
    <h2 class="text-gray-500 text-sm">Total Participants</h2>
    <p class="text-3xl font-bold text-blue-600 mt-2">{{ total_participants }}</p>
  </div>
  <div class="bg-white shadow-lg rounded-2xl p-6 hover:shadow-xl transition">
    <h2 class="text-gray-500 text-sm">Total Events</h2>
    <p class="text-3xl font-bold text-blue-600 mt-2">{{ total_events }}</p>
  </div>
  <div class="bg-white shadow-lg rounded-2xl p-6 hover:shadow-xl transition">
    <h2 class="text-gray-500 text-sm">Upcoming Events</h2>
    <p class="text-3xl font-bold text-green-600 mt-2">{{ upcoming_events }}</p>
  </div>
  <div class="bg-white shadow-lg rounded-2xl p-6 hover:shadow-xl transition">
    <h2 class="text-gray-500 text-sm">Past Events</h2>
    <p class="text-3xl font-bold text-red-600 mt-2">{{ past_events }}</p>
  </div>
</div>


<!-- Action Buttons -->
<div class="my-16 flex flex-col sm:flex-row gap-4 justify-center w-fit mx-auto">
  <a href="{% url 'participant_list' %}" class="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600 transition text-center">Manage Participants</a>
  <a href="{% url 'category_list' %}" class="bg-green-500 text-white px-4 py-2 rounded hover:bg-green-600 transition text-center">Manage Categories</a>
  <a href="{% url 'add_event' %}" class="bg-purple-500 text-white px-4 py-2 rounded hover:bg-purple-600 transition text-center">Add Event</a> 
 
</div>

{% endblock %}

users/templates/users/participant_dashboard.html
{% extends "base.html" %}
{% load static %}

{% block title %}Participant Dashboard | Triple Events{% endblock %}

{% block content %}
<div class="max-w-6xl mx-auto py-10 px-4">
  <h1 class="text-3xl font-bold text-blue-700 text-center mb-8">
    🎉 Welcome to Your Dashboard, {{ request.user.first_name|default:request.user.username }}!
  </h1>

  <div class="bg-white shadow-md rounded-lg p-6 text-center">
    <p class="text-lg text-gray-700 mb-4">
      As a participant, you can explore all available events, register, and stay updated!
    </p>
    <div class="flex flex-col sm:flex-row justify-center gap-4 mt-6">
      <a href="{% url 'all_events' %}" class="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600 transition">
        Browse All Events
      </a>
      <a href="{% url 'search_events' %}" class="bg-gray-500 text-white px-4 py-2 rounded hover:bg-gray-600 transition">
        Search Events
      </a>
    </div>
  </div>

  <div class="mt-10 text-center text-gray-500 text-sm">
    If you think you're assigned the wrong role, contact the admin.
  </div>




</div>
{% endblock %}

users/templates/users/promote_from_participants.html
{% extends "base.html" %}
{% block title %}Promote Participants{% endblock %}

{% block content %}
  <h1 class="text-2xl font-bold mb-6 my-8">Promote Participant to Organizer</h1>

  <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4">
    {% for participant in participants %}
      <div class="p-4 border rounded shadow">
        <p class="font-semibold">{{ participant.get_full_name|default:participant.username }}</p>
        <p class="text-sm text-gray-500">{{ participant.email }}</p>
        <form method="POST" class="mt-2">
          {% csrf_token %}
          <input type="hidden" name="user_id" value="{{ participant.id }}">
          <button type="submit" class="bg-green-600 text-white px-3 py-1 rounded hover:bg-green-700 text-sm">
            Promote to Organizer
          </button>
        </form>
      </div>
    {% empty %}
      <p>No participants found.</p>
    {% endfor %}
  </div>
{% endblock %}

users/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Create an Account | Event Management{% endblock %}

{% block content %}
<div class="flex justify-center items-center  mt-24 mb-16 px-4">
  <div class="bg-white shadow-2xl rounded-3xl w-full max-w-2xl p-10 sm:p-14">
    <div class="mb-10 text-center">
      <h2 class="text-4xl font-bold text-gray-800">Create your account</h2>
      <p class="text-gray-500 text-sm mt-2">Start managing and attending events</p>
    </div>

    <form method="POST" enctype="multipart/form-data" class="space-y-6">
      {% csrf_token %}
      {% for field in form %}
        <div>
          <label class="block text-gray-700 font-semibold mb-1">{{ field.label }}</label>
          {{ field }}
          {% if field.errors %}
            <p class="text-sm text-red-500 mt-1">{{ field.errors.0 }}</p>
          {% endif %}
        </div>
      {% endfor %}
      <button
        type="submit"
        class="w-full bg-blue-600 hover:bg-blue-700 transition-all text-white font-bold py-3 rounded-xl text-lg shadow-sm"
      >
        Sign Up
      </button>
    </form>

    <p class="text-sm text-gray-600 mt-6 text-center">
      Already have an account?
      <a href="{% url 'login' %}" class="text-blue-600 hover:underline font-semibold">Sign in here</a>
    </p>
  </div>
</div>
{% endblock %}